version: '3.8'

services:

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - backend
